export const validationErrorKeys = {
  UNKNOWN: 'VALIDATION_ERROR::UNKNOWN',
  MUST_BE_STRING: 'VALIDATION_ERROR::MUST_BE_STRING',
  STRING_TOO_SHORT: 'VALIDATION_ERROR::STRING_TOO_SHORT',
  STRING_TOO_LONG: 'VALIDATION_ERROR::STRING_TOO_LONG',
};

export const inputErrorKeys = {
  TOPIC_NOT_FOUND: 'INPUT_ERROR::TOPIC_NOT_FOUND',
};

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const INPUT_ERROR = 'INPUT_ERROR';

export const genericErrors = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
