export const validationErrorKeys = {
  UNKNOWN: 'VALIDATION_ERROR::UNKNOWN',
  MUST_BE_STRING: 'VALIDATION_ERROR::MUST_BE_STRING',
  STRING_TOO_SHORT: 'VALIDATION_ERROR::STRING_TOO_SHORT',
  STRING_TOO_LONG: 'VALIDATION_ERROR::STRING_TOO_LONG',
};

export const genericErrors = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
